name: Scheduled Subscribe
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  subscribe:
    name: "Subscribe"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install
        run: yarn install
      - name: Subscribe
        run: |
          for _ in 1 2; do npm run add-subscription-to-inoreader && break; done
        env:
          INOREADER_TOKEN_JSON: ${{ secrets.INOREADER_TOKEN_JSON }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          EXCLUDE_PATTERNS: ${{ secrets.EXCLUDE_PATTERNS }}
